# 사고데이터 분류
## 출력된 히트맵 데이터 이름에 따른 분류

In [29]:
import os
import pandas as pd
import numpy as np
import cv2
from shutil import move
import re

In [12]:
path = '../9.data/1.accData_split/'

In [13]:
acc_list = os.listdir(path + '0.acc_pattern_heatmap/accident/')
nonacc_list = os.listdir(path + '0.acc_pattern_heatmap/nonaccident/')
else_list = os.listdir(path + '0.acc_pattern_heatmap/else/')
diff_list = os.listdir(path + '1.diff_heatmap/')

acc_path = path + '0.acc_pattern_heatmap/accident/'
nonacc_path = path + '0.acc_pattern_heatmap/nonaccident/'
else_path = path + '0.acc_pattern_heatmap/else/'
diff_path = path + '1.diff_heatmap/'

In [11]:
for i in acc_list:
    img = cv2.imread(diff_path + i)
    cutImg = img[2530:4200, 1050:3450]
    cv2.imwrite(diff_path + 'accident/' +i, cutImg)

In [12]:
for i in nonacc_list:
    img = cv2.imread(diff_path + i)
    cutImg = img[2530:4200, 1050:3450]
    cv2.imwrite(diff_path + 'nonaccident/' +i, cutImg)

In [13]:
for i in else_list:
    img = cv2.imread(diff_path + i)
    cutImg = img[2530:4200, 1050:3450]
    cv2.imwrite(diff_path + 'else/' +i, cutImg)

In [1]:
1760+5887+1198

8845

## 분류된 이름에 따른 AccList 재분류

In [1]:
path_AL = '../9.data/0.work_data/3.Accident_list/'

AccList = pd.read_csv(path_AL + 'AccList.csv', header=None, index_col=0)

In [49]:
acclist = os.listdir(diff_path + 'accident/')
nonacclist = os.listdir(diff_path + 'nonaccident/')

for i in range(len(acclist)):
    acclist[i] = acclist[i].split('.')[0]
for i in range(len(nonacclist)):
    nonacclist[i] = nonacclist[i].split('.')[0]

In [53]:
AccList.loc[acclist]

1         2      3         4    \
0                                                                              
2018-02-06 Line1 RADR42 - accident#416   0.000000  0.000000  0.000  0.000000   
2018-02-06 Line4 RADR42 - accident#417   0.811111  0.325301  0.000  0.000000   
2018-02-08 Line1 RADR19 - accident#7569  0.000000  0.000000  0.000  0.000000   
2018-02-08 Line2 RADR18 - accident#7574  0.000000  0.000000  0.000  0.000000   
2018-02-08 Line2 RADR19 - accident#7576  0.000000  0.000000  0.000  0.000000   
...                                           ...       ...    ...       ...   
2019-10-30 Line4 RADR33 - accident#1191  0.315217  8.772727  6.325  5.970588   
2019-10-30 Line4 RADR34 - accident#1193  0.000000  1.179775  1.600  1.155340   
2019-10-30 Line4 RADR35 - accident#1194  0.000000  1.179775  1.600  1.155340   
2019-10-30 Line4 RADR36 - accident#1195  0.000000  1.179775  1.600  1.155340   
2019-10-30 Line4 RADR37 - accident#1197  0.000000  1.179775  1.600  1.155340   

                                              5         6         7    \
0                                                                       
2018-02-06 Line1 RADR42 - accident#416   0.870000  0.000000  0.000000   
2018-02-06 Line4 RADR42 - accident#417   0.000000  0.000000  0.000000   
2018-02-08 Line1 RADR19 - accident#7569  0.000000  0.000000  0.000000   
2018-02-08 Line2 RADR18 - accident#7574  0.000000  0.000000  0.000000   
2018-02-08 Line2 RADR19 - accident#7576  0.000000  0.000000  0.000000   
...                                           ...       ...       ...   
2019-10-30 Line4 RADR33 - accident#1191  7.425743  8.440000  4.645833   
2019-10-30 Line4 RADR34 - accident#1193  0.529412  1.226667  1.638298   
2019-10-30 Line4 RADR35 - accident#1194  0.529412  1.226667  1.638298   
2019-10-30 Line4 RADR36 - accident#1195  0.529412  1.226667  1.638298   
2019-10-30 Line4 RADR37 - accident#1197  0.529412  1.226667  1.638298   

                                              8         9    10   ...  \
0                                                                 ...   
2018-02-06 Line1 RADR42 - accident#416   0.000000  0.000000  0.0  ...   
2018-02-06 Line4 RADR42 - accident#417   0.000000  0.000000  0.0  ...   
2018-02-08 Line1 RADR19 - accident#7569  0.000000  0.000000  0.0  ...   
2018-02-08 Line2 RADR18 - accident#7574  0.000000  0.000000  0.0  ...   
2018-02-08 Line2 RADR19 - accident#7576  0.000000  0.000000  0.0  ...   
...                                           ...       ...  ...  ...   
2019-10-30 Line4 RADR33 - accident#1191  1.872549  1.621212  0.0  ...   
2019-10-30 Line4 RADR34 - accident#1193  0.603960  0.212121  0.0  ...   
2019-10-30 Line4 RADR35 - accident#1194  0.603960  0.212121  0.0  ...   
2019-10-30 Line4 RADR36 - accident#1195  0.603960  0.212121  0.0  ...   
2019-10-30 Line4 RADR37 - accident#1197  0.603960  0.212121  0.0  ...   

                                               552        553        554  \
0                                                                          
2018-02-06 Line1 RADR42 - accident#416    0.000000   0.000000   0.000000   
2018-02-06 Line4 RADR42 - accident#417    0.000000   0.000000   0.000000   
2018-02-08 Line1 RADR19 - accident#7569   0.000000   0.000000   0.000000   
2018-02-08 Line2 RADR18 - accident#7574   0.000000   0.000000   0.000000   
2018-02-08 Line2 RADR19 - accident#7576   0.000000   0.000000   0.000000   
...                                            ...        ...        ...   
2019-10-30 Line4 RADR33 - accident#1191  36.626374  28.808642  20.285714   
2019-10-30 Line4 RADR34 - accident#1193  35.966667  28.297468  18.716981   
2019-10-30 Line4 RADR35 - accident#1194  35.966667  28.297468  18.716981   
2019-10-30 Line4 RADR36 - accident#1195  35.966667  28.297468  18.716981   
2019-10-30 Line4 RADR37 - accident#1197  35.966667  28.297468  18.716981   

                                               555        556        557  \
0                                       

In [54]:
AccList.loc[nonacclist]

1          2          3    \
0                                                                           
2018-02-13 Line1 RADR14 - accident#2562    0.000000   0.000000   6.511111   
2018-02-13 Line1 RADR16 - accident#2545   30.755556  47.367816  53.170455   
2018-02-13 Line1 RADR16 - accident#2546    0.000000   0.000000   6.511111   
2018-02-22 Line1 RADR14 - accident#7585    0.306818   0.000000   1.057471   
2018-02-22 Line1 RADR15 - accident#7578    0.590909   2.837209   1.593023   
...                                             ...        ...        ...   
2019-03-31 Line2 RADR15 - accident#16600   0.000000   0.000000   0.000000   
2019-03-31 Line2 RADR16 - accident#16601   1.044944   1.241379   1.862069   
2019-03-31 Line2 RADR16 - accident#16602   1.727273   2.883721   3.767442   
2019-03-31 Line2 RADR17 - accident#16605   0.000000   0.000000  10.215909   
2019-10-26 Line4 RADR41 - accident#5773    2.225806   3.552941   0.000000   

                                                4          5          6    \
0                                                                           
2018-02-13 Line1 RADR14 - accident#2562   22.922222  28.000000  33.222222   
2018-02-13 Line1 RADR16 - accident#2545   50.965909  51.631579  48.594937   
2018-02-13 Line1 RADR16 - accident#2546   22.922222  28.000000  33.222222   
2018-02-22 Line1 RADR14 - accident#7585    1.188889   0.285714   0.000000   
2018-02-22 Line1 RADR15 - accident#7578    2.301075   1.459770   0.000000   
...                                             ...        ...        ...   
2019-03-31 Line2 RADR15 - accident#16600   9.358696  18.882353  12.488372   
2019-03-31 Line2 RADR16 - accident#16601   0.000000   0.000000   0.000000   
2019-03-31 Line2 RADR16 - accident#16602   3.520833   3.806818   3.820225   
2019-03-31 Line2 RADR17 - accident#16605  17.642105  20.397727  12.865169   
2019-10-26 Line4 RADR41 - accident#5773    0.000000   0.000000   0.000000   

                                                7          8          9    \
0                                                                           
2018-02-13 Line1 RADR14 - accident#2562   30.523810  27.454545  25.377778   
2018-02-13 Line1 RADR16 - accident#2545   44.523256  32.808081  37.063830   
2018-02-13 Line1 RADR16 - accident#2546   30.523810  27.454545  25.377778   
2018-02-22 Line1 RADR14 - accident#7585    0.000000   0.000000   1.488372   
2018-02-22 Line1 RADR15 - accident#7578    0.000000   0.000000   0.000000   
...                                             ...        ...        ...   
2019-03-31 Line2 RADR15 - accident#16600  15.576087  13.865385  10.259259   
2019-03-31 Line2 RADR16 - accident#16601   0.000000   0.880000   1.423077   
2019-03-31 Line2 RADR16 - accident#16602   0.133333   0.088235   0.000000   
2019-03-31 Line2 RADR17 - accident#16605  15.155556  13.078431   6.056604   
2019-10-26 Line4 RADR41 - accident#5773    0.000000   0.000000   0.000000   

                                                10   ...        552  \
0                                                    ...              
2018-02-13 Line1 RADR14 - accident#2562   19.311111  ...   0.000000   
2018-02-13 Line1 RADR16 - accident#2545   26.829787  ...   0.000000   
2018-02-13 Line1 RADR16 - accident#2546   19.311111  ...   0.000000   
2018-02-22 Line1 RADR14 - accident#7585    0.465116  ...   0.000000   
2018-02-22 Line1 RADR15 - accident#7578    0.000000  ...   0.000000   
...                                             ...  ...        ...   
2019-03-31 Line2 RADR15 - accident#16600   5.925926  ...   3.116279   
2019-03-31 Line2 RADR16 - accident#16601   4.730769  ...   0.000000   
2019-03-31 Line2 RADR16 - accident#16602   2.754717  ...  18.581395   
2019-03-31 Line2 RADR17 - accident#16605   3.867925  ...   0.825581   
2019-10-26 Line4 RADR41 - accident#5773    0.000000  ...   0.000000   

                                                553        554        555  \
0                                        

## 사고아닌 데이터 히트맵 자르기

In [2]:
path = '../9.data/0.work_data/2.heatmap/1.nonaccident/2.test/'

In [3]:
nonaccList = os.listdir(path)

In [4]:
for i in nonaccList:
    img = cv2.imread(path + i)
    cutImg = img[2530:4200, 1050:3450]
    cv2.imwrite('../9.data/1.accData_split/2.last/' +i, cutImg)


# 사고데이터 분석

## 사고로 분류된 데이터 분석

In [2]:
path = '../9.data/0.work_data/2.heatmap/0.accident/0.히트맵/'

In [12]:
dataList = os.listdir(path)

In [35]:
data = []
for i in dataList:
    data.append(i.split(' '))

In [21]:
len(data)

8839

In [36]:
SangLineNum = np.zeros(4)
HaLineNum = np.zeros(4)

for i in range(len(data)):
    if int(re.findall('\d+',data[i][2])[0]) > 30:
        if data[i][1] == '1차선':
            HaLineNum[0] += 1
        elif data[i][1] == '2차선':
            HaLineNum[1] += 1
        elif data[i][1] == '3차선':
            HaLineNum[2] += 1
        else:
            HaLineNum[3] += 1
    else:
        if data[i][1] == '1차선':
            SangLineNum[0] += 1
        elif data[i][1] == '2차선':
            SangLineNum[1] += 1
        elif data[i][1] == '3차선':
            SangLineNum[2] += 1
        else:
            SangLineNum[3] += 1

In [37]:
SangLineNum

array([1883., 1881.,  273.,   83.])

In [40]:
HaLineNum.sum()

4719.0

In [39]:
SangLineNum.sum()

4120.0

In [49]:
int(data[0][0].split('-')[0])
int(data[0][0].split('-')[1])
int(data[0][0].split('-')[2])

2

In [52]:
from datetime import date

def printDayOfTheWeek (year, month, day):
    dayOfTheWeek = ["월요일", "화요일", "수요일", "목요일", "금요일", "토요일", "일요일"]
    return dayOfTheWeek[date(year, month, day).weekday()]


In [55]:
HaWeekday = np.zeros(7)
SangWeekday = np.zeros(7)
for i in range(len(data)):
    if int(re.findall('\d+',data[i][2])[0]) > 30:
        if printDayOfTheWeek(int(data[i][0].split('-')[0]),int(data[i][0].split('-')[1]),int(data[i][0].split('-')[2])) == '월요일':
            HaWeekday[0] += 1
        elif printDayOfTheWeek(int(data[i][0].split('-')[0]),int(data[i][0].split('-')[1]),int(data[i][0].split('-')[2])) == '화요일':
            HaWeekday[1] += 1
        elif printDayOfTheWeek(int(data[i][0].split('-')[0]),int(data[i][0].split('-')[1]),int(data[i][0].split('-')[2])) == '수요일':
            HaWeekday[2] += 1
        elif printDayOfTheWeek(int(data[i][0].split('-')[0]),int(data[i][0].split('-')[1]),int(data[i][0].split('-')[2])) == '목요일':
            HaWeekday[3] += 1
        elif printDayOfTheWeek(int(data[i][0].split('-')[0]),int(data[i][0].split('-')[1]),int(data[i][0].split('-')[2])) == '금요일':
            HaWeekday[4] += 1
        elif printDayOfTheWeek(int(data[i][0].split('-')[0]),int(data[i][0].split('-')[1]),int(data[i][0].split('-')[2])) == '토요일':
            HaWeekday[5] += 1
        else:
            HaWeekday[6] += 1
    else:
        if printDayOfTheWeek(int(data[i][0].split('-')[0]),int(data[i][0].split('-')[1]),int(data[i][0].split('-')[2])) == '월요일':
            SangWeekday[0] += 1
        elif printDayOfTheWeek(int(data[i][0].split('-')[0]),int(data[i][0].split('-')[1]),int(data[i][0].split('-')[2])) == '화요일':
            SangWeekday[1] += 1
        elif printDayOfTheWeek(int(data[i][0].split('-')[0]),int(data[i][0].split('-')[1]),int(data[i][0].split('-')[2])) == '수요일':
            SangWeekday[2] += 1
        elif printDayOfTheWeek(int(data[i][0].split('-')[0]),int(data[i][0].split('-')[1]),int(data[i][0].split('-')[2])) == '목요일':
            SangWeekday[3] += 1
        elif printDayOfTheWeek(int(data[i][0].split('-')[0]),int(data[i][0].split('-')[1]),int(data[i][0].split('-')[2])) == '금요일':
            SangWeekday[4] += 1
        elif printDayOfTheWeek(int(data[i][0].split('-')[0]),int(data[i][0].split('-')[1]),int(data[i][0].split('-')[2])) == '토요일':
            SangWeekday[5] += 1
        else:
            SangWeekday[6] += 1

In [60]:
SangWeekday

array([342., 488., 494., 785., 785., 688., 538.])

In [61]:
HaWeekday

array([ 218.,  208.,  342.,  342.,  796., 2390.,  423.])